# Requires docker 1.10.0+ and docker-compose 1.6.0+.
version: '2'
services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    volumes:
      - ./socorro-collector:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DEBUG=True
    command: ./run_gunicorn.sh
